// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "$nOYQPOOO_QPO'#C`OOQO'#Cp'#CpOdQPOOOOQO'#Cb'#CbOlQPO,58zOOQO-E6n-E6nO}QPO'#ClOOQO'#Cr'#CrQgQPOOO_QPO'#CdO!SQPO'#CfO!XQPO'#CiOOQO1G.f1G.fO!^QPO1G.fOOQO'#Cn'#CnO!lQPO,59WOOQO-E6p-E6pOOQO'#Cq'#CqO!qQPO,59OOOQO,59Q,59QO#SQPO,59TOOQO7+$Q7+$QO_QPO1G.rOOQO-E6o-E6oO#XQPO1G.oO#^QPO7+$^OOQO7+$Z7+$Z",
  stateData: "#i~OPOSQOS~OTPO~OVSO~OTPOaVO~OXYOZZO^[OTSaaSa~OV_O~O[dO~O[eO~OZZO^[OTSiaSi~OcgO~OVSOTWaZWa^WaaWa~O_iO~O[kO~OVSOa`qg`q~O",
  goto: "!mgPPPPhPlPuPxPPxPP!OP!SP!V!]!gTQORQTPXbYcgjR^TQ]TRf^TWRXR`VQRORURQcYShcjRjgQXRRaX",
  nodeNames: "⚠ Whitespace Comment Program TaskStatement TaskKW TaskName String DependencyClause DependsOnKW CostClause CostsKW Integer SpanClause SpansKW DashKW ParticipantStatement ParticipantKW ParticipantName ColonKW",
  maxTerm: 24,
  skippedNodes: [0,1,2],
  repeatNodeCount: 3,
  tokenData: "(h~R^XY}YZ}]^}pq}rs!`st#T}!O#o!Q![#t![!]#|#V#W$R#W#X$p#d#e%}#g#h'b#h#i(P~!SSP~XY}YZ}]^}pq}~!cVOY!`Z]!`^r!`rs!xs;'S!`;'S;=`!}<%lO!`~!}OV~~#QP;=`<%l!`~#YTQ~OY#TZ]#T^;'S#T;'S;=`#i<%lO#T~#lP;=`<%l#T~#tO_~~#yP[~!Q![#t~$ROc~~$UP#c#d$X~$[P#g#h$_~$bP#h#i$e~$hP#g#h$k~$pOZ~~$sP#X#Y$v~$yP#d#e$|~%PP#X#Y%S~%VP#b#c%Y~%]P#W#X%`~%cP#g#h%f~%iPpq%l~%oP#c#d%r~%uP#b#c%x~%}OX~~&QP#T#U&T~&WP#f#g&Z~&^P#h#i&a~&dP#]#^&g~&jP#V#W&m~&pP#]#^&s~&vP#d#e&y~&|P#T#U'P~'SP#b#c'V~'YP#h#i']~'bOa~~'eP#d#e'h~'kP#T#U'n~'qP#b#c't~'wP#g#h'z~(PO^~~(SP#T#U(V~(YP#g#h(]~(`P#_#`(c~(hOT~",
  tokenizers: [0],
  topRules: {"Program":[0,3]},
  tokenPrec: 0
})
